name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every day
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.gyford.com/phil/feeds/everything/rss/https://blog.kernelanxiety.dev/index.xmlhttps://dsaikrishna.substack.com/feedhttps://sathyabh.at/index.xmlhttps://goinggnu.wordpress.com/feedhttps://feeds.thejeshgn.com/thejeshgnhhttps://sridhar.co/rss.xmlhttps://jamesvandyne.com/feed/https://danielsantos.org/feed/https://tracydurnell.com/feed/https://maique.eu/feed.xmlhttps://justdev.blogspot.com/feeds/posts/defaulthttps://mihobu.lol/rss.xmlhttps://vishnugopal.com/feedhttps://www.haripriya.org/blog-feed.xmlhttps://www.matratype.com/week-notes?format=rsshttps://www.thejaymo.net/feed/https://anhvn.com/feed.xmlhttps://alicebartlett.co.uk/feed.xmlhttps://tomstu.art/feed.atomhttps://blog.annkempster.com/rss/https://denisdefreyne.com/feed.xmlhttps://www.timothymonger.com/isthissomething?format=rsshttps://jeffmcneill.com/feed/https://rowanmanning.com/posts/feed.xmlhttp://www.s-anand.net/blog/feed/https://walknotes.com/feed/https://pradx.in/feed/https://lapope.com/category/week-notes/feed/https://rogerswannell.com/feed/https://ankursethi.in/blog/feed/https://mmitii.mattballantine.com/feed/https://webcurios.co.uk/feed/https://digitalbydefault.com/feed/https://mb.esamecar.net/feed.xmlhttps://blog.mattedgar.com/feed/"
          max_post_count: 100
