name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every day
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.gyford.com/phil/feeds/everything/rss/,https://blog.kernelanxiety.dev/index.xml,https://dsaikrishna.substack.com/feed,https://sathyabh.at/index.xml,https://goinggnu.wordpress.com/feed,https://feeds.thejeshgn.com/thejeshgn,hhttps://sridhar.co/rss.xml,https://jamesvandyne.com/feed/,https://danielsantos.org/feed/,https://tracydurnell.com/feed/,https://maique.eu/feed.xml,https://justdev.blogspot.com/feeds/posts/default,https://mihobu.lol/rss.xml,https://vishnugopal.com/feed,https://www.haripriya.org/blog-feed.xml,https://www.matratype.com/week-notes?format=rss,https://www.thejaymo.net/feed/,https://anhvn.com/feed.xml,https://alicebartlett.co.uk/feed.xml,https://tomstu.art/feed.atom,https://blog.annkempster.com/rss/,https://denisdefreyne.com/feed.xml,https://www.timothymonger.com/isthissomething?format=rss,https://jeffmcneill.com/feed/,https://rowanmanning.com/posts/feed.xml,http://www.s-anand.net/blog/feed/,https://walknotes.com/feed/,https://pradx.in/feed/,https://lapope.com/category/week-notes/feed/,https://rogerswannell.com/feed/,https://ankursethi.in/blog/feed/,https://mmitii.mattballantine.com/feed/,https://webcurios.co.uk/feed/,https://digitalbydefault.com/feed/,https://mb.esamecar.net/feed.xml,https://blog.mattedgar.com/feed/"
          max_post_count: 100
